TRAIN:
  ENABLE: True
#  DATASET: Egoexo4d
  DATASET: Egoexo4d_gen2
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: '/home/wchi/Datasets/EgoExo4D/annotations/csvs/keystep_segments/ego/'
#  PATH_TO_DATA_DIR: '/home/wchi/Datasets/EgoExo4D/annotations/csvs/keystep_segments/ego_swap_train_test/'
#  PATH_TO_DATA_DIR: '/home/wchi/Datasets/EgoExo4D/annotations/csvs/keystep_segments/exo_best/'
#  PATH_TO_DATA_DIR: '/home/wchi/Datasets/EgoExo4D/annotations/csvs/keystep_segments/exo/'
#  PATH_TO_DATA_DIR: '/home/wchi/Datasets/EgoExo4D/annotations/csvs/keystep_segments/exo_swap_train_test/'
#  PATH_PREFIX: '/home/wchi/Datasets/EgoExo4D/keystep_segments'
  PATH_PREFIX: '/home/wchi/Datasets/EgoExo4D/keystep_segments_paired'
  EXO_FEAT_DIR: '/home/wchi/Datasets/EgoExo4D/tsf_EE4D_best_feats'
  EXO_FEAT_DIR_SKL: '/home/wchi/Datasets/EgoExo4D/gcn_EE4D_best_feats'
  EXO_LOGITS_DIR: '/home/wchi/Datasets/EgoExo4D/tsf_EE4D_best_logits'
  EXO_LOGITS_DIR_SKL: '/home/wchi/Datasets/EgoExo4D/gcn_EE4D_best_logits'

  SKL_MODEL_BY_LOGITS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/skl_model_by_L'
  SKL_MODEL_BY_FEATS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/skl_model_by_F'
  SKL_MODEL_BY_FEATS_AND_LOGITS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/skl_model_by_F_L'
  RGB_MODEL_BY_LOGITS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/rgb_model_by_L'
  RGB_MODEL_BY_FEATS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/rgb_model_by_F'
  RGB_MODEL_BY_FEATS_AND_LOGITS: '/home/wchi/Projects/TimeSformer/models/EE4D_gen1/rgb_model_by_F_L'
  MERGED_MODEL: '/home/wchi/Projects/TimeSformer/models/merged_checkpoints/EE4D_gen1/TOP_6_model_level'
  LOGITS_DIR: 'scores_pred_train'
  FEATS_DIR: 'tokens'

  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
#  PRETRAINED_MODEL: pretrained_models/TimeSformer_divST_8x32_224_K400.pyth
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
#  LR_POLICY: cosine
#  LR_POLICY: cosine_sequential
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 665
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: Assembly101
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
#  SAVE_RESULTS_PATH: 'scores_pred'
  SAVE_RESULTS_PATH: 'scores_pred_train'
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0


#OUTPUT_DIR: ./models/EE4D_gen1/skl_model_by_F_L
OUTPUT_DIR: ./models/merged_checkpoints/EE4D_gen2/top_6_w_decay_lr0_02_mse_w10_FL_wo_cond
#OUTPUT_DIR: ./models/EE4D_gen2/Global_best_teacher_cos_F_w10_L_w10_th_4_proximal_TOP_4
#OUTPUT_DIR: ./models/EE4D_visual/rgb_skl

TOKEN_SAVE_DIR: tokens
SAVE_TOKENS: TRUE

#TRAINING_MODE: 'basic'
#TRAINING_MODE: 'dist'
TRAINING_MODE: 'dist_merged'
#TRAINING_MODE: 'dit'

#TRAINING_SCHEME: [15, 15, 5, 15, 5, 15, 5, 15, 10]

# MUST BE EMPTY WHEN SAVING TRAINING TOKENS
#EXO_MODALITY: ['logits_skl', 'skl']
#EXO_MODALITY: ['logits_skl']
#EXO_MODALITY: ['skl']
#EXO_MODALITY: ['logits', 'rgb']
#EXO_MODALITY: ['logits']
#EXO_MODALITY: ['feats']
#EXO_MODALITY: ['logits', 'logits_skl']

#EXO_MODALITY: ['rgb']
#EXO_MODALITY: ['skl', 'rgb']
#EXO_MODALITY: ['auto']
EXO_MODALITY: ['logits', 'feats']
#EXO_MODALITY: ['logits', 'feats', 'random']
#EXO_MODALITY: ['logits', 'feats', 'average']

GENERATION: 'gen2' # 'gen1' or 'gen2'
#LOSS_TYPE: 'cosine'
LOSS_TYPE: 'mse'
#OPT_SPACE: 'logits' # 'feats' or 'logits'
LOSS_WEIGHT: 5.0
LOSS_WEIGHT_FEATS: 10.0
LOSS_WEIGHT_LOGITS: 10.0
DIST_THRESHOLD: 4.0
TOP_K: 1


#----------Check List-------------
# 1) DATA.PATH_TO_DATA_DIR
# 2) OUTPUT_DIR
# 3) SAVE_TOKENS
# 4) TRAINING_MODE
# 5) EXO_MODALITY
#---------------------------------
